# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8fe493e66e4b52a3010655c9c24ecbb8b5d2946b82a81d400b97b8d193b0c28a865ad07d479b0fb1fc41baf88f18daccc7a91ba5d35e3ed70c103bb7174c4aa

test:
  secret_key_base: 32319975520a70f2cec408f4ce2d5f32e531f929d5101a40d17b05834d734d70ba967c9ebc57a9817e4d939ca58cc476703dff56c77a3f6a85909739e51d610c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
